import { type ReactElement } from 'react';

import { ViewVariableType } from '@coze-workflow/base';
import {
  IconCozNumber,
  IconCozString,
  IconCozBoolean,
  IconCozFolder,
  IconCozBrace,
  IconCozImage,
  IconCozStringBracket,
  IconCozImageBracket,
  IconCozBooleanBracket,
  IconCozNumberBracket,
  IconCozNumberInt,
  IconCozNumberIntBracket,
  IconCozBraceBracket,
  IconCozFolderBracket,
  IconCozSound,
  IconCozClock,
  IconCozClockBracket,
} from '@coze-arch/coze-design/icons';

const iconFile = <IconCozFolder />;
const iconFileArray = <IconCozFolderBracket />;
export const VARIABLE_TYPE_ICON_MAP: Record<ViewVariableType, ReactElement> = {
  [ViewVariableType.String]: <IconCozString />,
  [ViewVariableType.Integer]: <IconCozNumberInt />,
  [ViewVariableType.Number]: <IconCozNumber />,
  [ViewVariableType.Boolean]: <IconCozBoolean />,
  [ViewVariableType.Object]: <IconCozBrace />,
  [ViewVariableType.Image]: <IconCozImage />,
  [ViewVariableType.Time]: <IconCozClock />,
  [ViewVariableType.File]: iconFile,
  [ViewVariableType.Doc]: iconFile,
  [ViewVariableType.Code]: iconFile,
  [ViewVariableType.Ppt]: iconFile,
  [ViewVariableType.Txt]: iconFile,
  [ViewVariableType.Excel]: iconFile,
  [ViewVariableType.Audio]: iconFile,
  [ViewVariableType.Zip]: iconFile,
  [ViewVariableType.Video]: iconFile,
  [ViewVariableType.Svg]: iconFile,
  [ViewVariableType.Voice]: <IconCozSound />,
  [ViewVariableType.ArrayString]: <IconCozStringBracket />,
  [ViewVariableType.ArrayInteger]: <IconCozNumberIntBracket />,
  [ViewVariableType.ArrayNumber]: <IconCozNumberBracket />,
  [ViewVariableType.ArrayBoolean]: <IconCozBooleanBracket />,
  [ViewVariableType.ArrayObject]: <IconCozBraceBracket />,
  [ViewVariableType.ArrayImage]: <IconCozImageBracket />,
  [ViewVariableType.ArrayFile]: iconFileArray,
  [ViewVariableType.ArrayDoc]: iconFileArray,
  [ViewVariableType.ArrayCode]: iconFileArray,
  [ViewVariableType.ArrayPpt]: iconFileArray,
  [ViewVariableType.ArrayTxt]: iconFileArray,
  [ViewVariableType.ArrayExcel]: iconFileArray,
  [ViewVariableType.ArrayAudio]: iconFileArray,
  [ViewVariableType.ArrayZip]: iconFileArray,
  [ViewVariableType.ArrayVideo]: iconFileArray,
  [ViewVariableType.ArraySvg]: iconFileArray,
  [ViewVariableType.ArrayVoice]: iconFileArray,
  [ViewVariableType.ArrayTime]: <IconCozClockBracket />,
};
