export enum SchemaExtractorParserName {
  DEFAULT = 'default',
  INPUT_PARAMETERS = 'inputParameters',
  OUTPUTS = 'outputs',
  DATASET_PARAM = 'datasetParam',
  LLM_PARAM = 'llmParam',
  INTENTS = 'intents',
  CONCAT_RESULT = 'concatResult',
  CUSTOM_ARRAY_CONCAT_CHAR = 'customArrayConcatChar',
  CUSTOM_SPLIT_CHAR = 'customSplitChar',
  REF_INPUT_PARAMETER = 'refInputParameter',
  VARIABLE_ASSIGN = 'variableAssign',
  JSON_STRING_PARSER = 'jsonStringParser',
  IMAGE_REFERENCE_PARSER = 'imageReferenceParser',
  EXPRESSION_PARSER = 'expressionParser',
  VARIABLE_MERGE_GROUPS_PARSER = 'variableMergeGroupsParser',
  DB_FIELDS_PARSER = 'dbFieldsParser',
  DB_CONDITIONS_PARSER = 'dbConditionsParser',
}

export const SYSTEM_DELIMITERS = [
  '\n',
  '\t',
  '.',
  '。',
  ',',
  '，',
  ';',
  '；',
  ' ',
];
