// Code generated by hertz generator.

package coze

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _playground_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upsertpromptresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedraftbotinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbotcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbot0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _memoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsysvariableconfMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _plugin_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebotdefaultparamsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbotdefaultparamsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getplaygroundpluginlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginapisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getplugininfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getupdatedapisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerpluginmetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebotdefaultparamsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepluginmetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraftbotinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _variableMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectvariablelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprojectvariableMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _knowledgeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _datasetdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _documentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesliceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedatasetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _photoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatephotocaptionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listphotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _photodetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resegmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _progressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdocumentprogressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _table_schemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettableschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatetableschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdocumenttableinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
