// Code generated by hertz generator.

package coze

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _playground_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upsertpromptresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}
