// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	coze "code.byted.org/flow/opencoze/backend/api/router/coze"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	coze.Register(r)
}

