// Code generated by hertz generator.

package main

import (
	"context"

	"code.byted.org/flow/opencoze/backend/api/middleware"
	"code.byted.org/flow/opencoze/backend/api/router"
	"code.byted.org/flow/opencoze/backend/application"
	"code.byted.org/flow/opencoze/backend/infra/pkg/logs"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	ctx := context.Background()

	if err := application.Init(ctx); err != nil {
		panic("InitializeInfra failed, err=" + err.Error())
	}

	logs.SetLevel(logs.LevelDebug)

	s := server.Default()
	s.Use(middleware.ContextCacheMW())
	s.Use(middleware.SessionMW())
	s.Use(middleware.AccessLogMW())
	router.GeneratedRegister(s)
	s.Spin()
}
