// Code generated by hertz generator.

package main

import (
	handler "code.byted.org/flow/opencoze/backend/api/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
