/*
 * lark doc get
 *
 * Lark doc get.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package lark_api

type DocumentContentBody struct {
	// error code
	Code int32 `json:"code,omitempty"`
	// error message
	Msg  string                   `json:"msg,omitempty"`
	Data *DocumentContentBodyData `json:"data,omitempty"`
}
