/*
 * lark doc get
 *
 * Lark doc get.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package lark_api

type SheetGridProperties struct {
	FrozenRowCount    int32 `json:"frozen_row_count,omitempty"`
	FrozenColumnCount int32 `json:"frozen_column_count,omitempty"`
	RowCount          int32 `json:"row_count,omitempty"`
	ColumnCount       int32 `json:"column_count,omitempty"`
}
