/*
 * lark doc get
 *
 * Lark doc get.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package lark_api

type GetSheetUnitBodyValueRange struct {
	MajorDimension string                             `json:"majorDimension,omitempty"`
	Range_         string                             `json:"range,omitempty"`
	Revision       int32                              `json:"revision,omitempty"`
	Values         []GetSheetUnitBodyValueRangeValues `json:"values,omitempty"`
}
