package schema

import "code.byted.org/flow/opencoze/backend/domain/workflow/nodes"

type NodeSchema struct {
	// Configs are domain specific configurations with fixed config-key and pre-defined config value.
	// Will not take part in request-time field mapping, nor as node's static values.
	Configs any `json:"configs"`

	// Inputs are domain specific input fields with fixed field name, or user defined input fields with dynamic field name.
	// Can have either ref or literal as value.
	// Will take part in request-time field mapping, or as node's static values.
	Inputs []*nodes.InputField `json:"inputs"`

	// Outputs are domain specific output fields with fixed field name, or user defined output fields with dynamic field name.
	// Usually they do not have 'Source' information, as they are generated by node itself, not referenced from other nodes or set as static value.
	// In some cases, they can have 'Source' information, because they refer to outputs of inner workflow's nodes (such as Batch node's output),
	// or they just use static values (such as End node's output).
	Outputs map[string]*nodes.FieldInfo `json:"outputs"`
}
