// Code generated by hertz generator.

package ynet_agent

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ynet_agentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revertdraftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}
