export * from '@coze-project-ide/core';

export {
  type CustomTitleType,
  type ViewOptionRegisterService,
  type CustomPreferenceConfig,
  type CustomTitleChanged,
  LayoutPanelType,
  ToolbarAlign,
  ReactWidget,
  ViewManager,
  WidgetFactory,
  WidgetManager,
  CurrentResourceContext,
  ReactWidgetContext,
  ViewContribution,
  useCurrentWidget,
  useCurrentWidgetFromArea,
  useCurrentResource,
  Widget,
  StatefulWidget,
  ApplicationShell,
  LayoutRestorer,
  CustomPreferenceContribution,
  ViewService,
  FlowDockPanel,
  HoverService,
  MenuService,
  DebugService,
  DEBUG_BAR_DRAGGABLE,
  SplitWidget,
  BoxLayout,
  DockLayout,
  BoxPanel,
  SplitLayout,
  SplitPanel,
  createBoxLayout,
  createSplitLayout,
  PerfectScrollbar,
  DISABLE_HANDLE_EVENT,
  TabBarToolbar,
  ACTIVITY_BAR_CONTENT,
  ViewRenderer,
  DragService,
  CustomTabBar,
  TabBar,
  type DragPropsType,
  type PresetConfigType,
  type ToolbarItem,
} from '@coze-project-ide/view';
export { createDefaultPreset } from './create-default-preset';
export { type IDEClientOptions, IDEClientContext } from './types';
export * from './components';
