// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-studio/backend/domain/knowledge/internal/dal/model"
)

func newWebCrawlTask(db *gorm.DB, opts ...gen.DOOption) webCrawlTask {
	_webCrawlTask := webCrawlTask{}

	_webCrawlTask.webCrawlTaskDo.UseDB(db, opts...)
	_webCrawlTask.webCrawlTaskDo.UseModel(&model.WebCrawlTask{})

	tableName := _webCrawlTask.webCrawlTaskDo.TableName()
	_webCrawlTask.ALL = field.NewAsterisk(tableName)
	_webCrawlTask.ID = field.NewInt64(tableName, "id")
	_webCrawlTask.WebURL = field.NewString(tableName, "web_url")
	_webCrawlTask.Title = field.NewString(tableName, "title")
	_webCrawlTask.FileSize = field.NewInt64(tableName, "file_size")
	_webCrawlTask.FileID = field.NewString(tableName, "file_id")
	_webCrawlTask.SubPageCount = field.NewInt32(tableName, "sub_page_count")
	_webCrawlTask.ContentTosURL = field.NewString(tableName, "content_tos_url")
	_webCrawlTask.SublinkTosURI = field.NewString(tableName, "sublink_tos_uri")
	_webCrawlTask.Status = field.NewInt32(tableName, "status")
	_webCrawlTask.FailReason = field.NewString(tableName, "fail_reason")
	_webCrawlTask.CreatedAt = field.NewInt64(tableName, "created_at")
	_webCrawlTask.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_webCrawlTask.DeletedAt = field.NewField(tableName, "deleted_at")
	_webCrawlTask.AuthID = field.NewInt64(tableName, "auth_id")
	_webCrawlTask.LarkExtra = field.NewField(tableName, "lark_extra")

	_webCrawlTask.fillFieldMap()

	return _webCrawlTask
}

// webCrawlTask 网页爬取任务表
type webCrawlTask struct {
	webCrawlTaskDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键ID
	WebURL        field.String // 网页URL
	Title         field.String // 网页标题
	FileSize      field.Int64  // 文件大小（字节）
	FileID        field.String // 文件ID
	SubPageCount  field.Int32  // 子页面数量
	ContentTosURL field.String // 内容存储URL
	SublinkTosURI field.String // 子链接存储URI
	Status        field.Int32  // 状态: 0-初始化 1-抓取完成 2-抓取失败
	FailReason    field.String // 失败原因
	CreatedAt     field.Int64  // 创建时间（毫秒）
	UpdatedAt     field.Int64  // 更新时间（毫秒）
	DeletedAt     field.Field  // Delete Time
	AuthID        field.Int64
	LarkExtra     field.Field // lark extra info

	fieldMap map[string]field.Expr
}

func (w webCrawlTask) Table(newTableName string) *webCrawlTask {
	w.webCrawlTaskDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webCrawlTask) As(alias string) *webCrawlTask {
	w.webCrawlTaskDo.DO = *(w.webCrawlTaskDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webCrawlTask) updateTableName(table string) *webCrawlTask {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.WebURL = field.NewString(table, "web_url")
	w.Title = field.NewString(table, "title")
	w.FileSize = field.NewInt64(table, "file_size")
	w.FileID = field.NewString(table, "file_id")
	w.SubPageCount = field.NewInt32(table, "sub_page_count")
	w.ContentTosURL = field.NewString(table, "content_tos_url")
	w.SublinkTosURI = field.NewString(table, "sublink_tos_uri")
	w.Status = field.NewInt32(table, "status")
	w.FailReason = field.NewString(table, "fail_reason")
	w.CreatedAt = field.NewInt64(table, "created_at")
	w.UpdatedAt = field.NewInt64(table, "updated_at")
	w.DeletedAt = field.NewField(table, "deleted_at")
	w.AuthID = field.NewInt64(table, "auth_id")
	w.LarkExtra = field.NewField(table, "lark_extra")

	w.fillFieldMap()

	return w
}

func (w *webCrawlTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webCrawlTask) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 15)
	w.fieldMap["id"] = w.ID
	w.fieldMap["web_url"] = w.WebURL
	w.fieldMap["title"] = w.Title
	w.fieldMap["file_size"] = w.FileSize
	w.fieldMap["file_id"] = w.FileID
	w.fieldMap["sub_page_count"] = w.SubPageCount
	w.fieldMap["content_tos_url"] = w.ContentTosURL
	w.fieldMap["sublink_tos_uri"] = w.SublinkTosURI
	w.fieldMap["status"] = w.Status
	w.fieldMap["fail_reason"] = w.FailReason
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["deleted_at"] = w.DeletedAt
	w.fieldMap["auth_id"] = w.AuthID
	w.fieldMap["lark_extra"] = w.LarkExtra
}

func (w webCrawlTask) clone(db *gorm.DB) webCrawlTask {
	w.webCrawlTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webCrawlTask) replaceDB(db *gorm.DB) webCrawlTask {
	w.webCrawlTaskDo.ReplaceDB(db)
	return w
}

type webCrawlTaskDo struct{ gen.DO }

type IWebCrawlTaskDo interface {
	gen.SubQuery
	Debug() IWebCrawlTaskDo
	WithContext(ctx context.Context) IWebCrawlTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebCrawlTaskDo
	WriteDB() IWebCrawlTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebCrawlTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebCrawlTaskDo
	Not(conds ...gen.Condition) IWebCrawlTaskDo
	Or(conds ...gen.Condition) IWebCrawlTaskDo
	Select(conds ...field.Expr) IWebCrawlTaskDo
	Where(conds ...gen.Condition) IWebCrawlTaskDo
	Order(conds ...field.Expr) IWebCrawlTaskDo
	Distinct(cols ...field.Expr) IWebCrawlTaskDo
	Omit(cols ...field.Expr) IWebCrawlTaskDo
	Join(table schema.Tabler, on ...field.Expr) IWebCrawlTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebCrawlTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebCrawlTaskDo
	Group(cols ...field.Expr) IWebCrawlTaskDo
	Having(conds ...gen.Condition) IWebCrawlTaskDo
	Limit(limit int) IWebCrawlTaskDo
	Offset(offset int) IWebCrawlTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebCrawlTaskDo
	Unscoped() IWebCrawlTaskDo
	Create(values ...*model.WebCrawlTask) error
	CreateInBatches(values []*model.WebCrawlTask, batchSize int) error
	Save(values ...*model.WebCrawlTask) error
	First() (*model.WebCrawlTask, error)
	Take() (*model.WebCrawlTask, error)
	Last() (*model.WebCrawlTask, error)
	Find() ([]*model.WebCrawlTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WebCrawlTask, err error)
	FindInBatches(result *[]*model.WebCrawlTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WebCrawlTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebCrawlTaskDo
	Assign(attrs ...field.AssignExpr) IWebCrawlTaskDo
	Joins(fields ...field.RelationField) IWebCrawlTaskDo
	Preload(fields ...field.RelationField) IWebCrawlTaskDo
	FirstOrInit() (*model.WebCrawlTask, error)
	FirstOrCreate() (*model.WebCrawlTask, error)
	FindByPage(offset int, limit int) (result []*model.WebCrawlTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebCrawlTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webCrawlTaskDo) Debug() IWebCrawlTaskDo {
	return w.withDO(w.DO.Debug())
}

func (w webCrawlTaskDo) WithContext(ctx context.Context) IWebCrawlTaskDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webCrawlTaskDo) ReadDB() IWebCrawlTaskDo {
	return w.Clauses(dbresolver.Read)
}

func (w webCrawlTaskDo) WriteDB() IWebCrawlTaskDo {
	return w.Clauses(dbresolver.Write)
}

func (w webCrawlTaskDo) Session(config *gorm.Session) IWebCrawlTaskDo {
	return w.withDO(w.DO.Session(config))
}

func (w webCrawlTaskDo) Clauses(conds ...clause.Expression) IWebCrawlTaskDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webCrawlTaskDo) Returning(value interface{}, columns ...string) IWebCrawlTaskDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webCrawlTaskDo) Not(conds ...gen.Condition) IWebCrawlTaskDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webCrawlTaskDo) Or(conds ...gen.Condition) IWebCrawlTaskDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webCrawlTaskDo) Select(conds ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webCrawlTaskDo) Where(conds ...gen.Condition) IWebCrawlTaskDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webCrawlTaskDo) Order(conds ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webCrawlTaskDo) Distinct(cols ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webCrawlTaskDo) Omit(cols ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webCrawlTaskDo) Join(table schema.Tabler, on ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webCrawlTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webCrawlTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webCrawlTaskDo) Group(cols ...field.Expr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webCrawlTaskDo) Having(conds ...gen.Condition) IWebCrawlTaskDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webCrawlTaskDo) Limit(limit int) IWebCrawlTaskDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webCrawlTaskDo) Offset(offset int) IWebCrawlTaskDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webCrawlTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebCrawlTaskDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webCrawlTaskDo) Unscoped() IWebCrawlTaskDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webCrawlTaskDo) Create(values ...*model.WebCrawlTask) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webCrawlTaskDo) CreateInBatches(values []*model.WebCrawlTask, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webCrawlTaskDo) Save(values ...*model.WebCrawlTask) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webCrawlTaskDo) First() (*model.WebCrawlTask, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebCrawlTask), nil
	}
}

func (w webCrawlTaskDo) Take() (*model.WebCrawlTask, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebCrawlTask), nil
	}
}

func (w webCrawlTaskDo) Last() (*model.WebCrawlTask, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebCrawlTask), nil
	}
}

func (w webCrawlTaskDo) Find() ([]*model.WebCrawlTask, error) {
	result, err := w.DO.Find()
	return result.([]*model.WebCrawlTask), err
}

func (w webCrawlTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WebCrawlTask, err error) {
	buf := make([]*model.WebCrawlTask, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webCrawlTaskDo) FindInBatches(result *[]*model.WebCrawlTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webCrawlTaskDo) Attrs(attrs ...field.AssignExpr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webCrawlTaskDo) Assign(attrs ...field.AssignExpr) IWebCrawlTaskDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webCrawlTaskDo) Joins(fields ...field.RelationField) IWebCrawlTaskDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webCrawlTaskDo) Preload(fields ...field.RelationField) IWebCrawlTaskDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webCrawlTaskDo) FirstOrInit() (*model.WebCrawlTask, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebCrawlTask), nil
	}
}

func (w webCrawlTaskDo) FirstOrCreate() (*model.WebCrawlTask, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WebCrawlTask), nil
	}
}

func (w webCrawlTaskDo) FindByPage(offset int, limit int) (result []*model.WebCrawlTask, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webCrawlTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webCrawlTaskDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webCrawlTaskDo) Delete(models ...*model.WebCrawlTask) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webCrawlTaskDo) withDO(do gen.Dao) *webCrawlTaskDo {
	w.DO = *do.(*gen.DO)
	return w
}
