CREATE TABLE IF NOT EXISTS `workflow_execution` (
    id bigint unsigned not null comment 'execute id' primary key,
    workflow_id bigint unsigned not null comment 'workflow_id',
    version varchar(50) null comment 'workflow version. empty if is draft',
    space_id bigint unsigned not null comment 'the space id the workflow belongs to',
    mode tinyint unsigned not null comment 'the execution mode: 1. debug run 2. release run 3. node debug',
    operator_id bigint unsigned not null comment 'the user id that runs this workflow',
    connector_id bigint unsigned null comment 'the connector on which this execution happened',
    connector_uid varchar(64) null comment 'user id of the connector',
    created_at bigint unsigned not null comment 'create time in millisecond',
    log_id varchar(128) null comment 'log id',
    status tinyint unsigned null comment '1=running 2=success 3=fail 4=interrupted',
    duration bigint unsigned null comment 'execution duration in millisecond',
    input mediumtext null comment 'actual input of this execution',
    output mediumtext null comment 'the actual output of this execution',
    error_code varchar(255) null comment 'error code if any',
    fail_reason mediumtext null comment 'the reason for failure',
    input_tokens bigint unsigned null comment 'number of input tokens',
    output_tokens bigint unsigned null comment 'number of output tokens',
    updated_at bigint unsigned null comment 'update time in millisecond',
    root_execution_id bigint unsigned null comment 'the top level execution id. Null if this is the root',
    parent_node_id varchar(128) null comment 'the node key for the sub_workflow node that executes this workflow',
    app_id bigint unsigned null comment 'app id this workflow execution belongs to',
    node_count mediumint unsigned null comment 'the total node count of the workflow',
    resume_event_id   bigint unsigned    null comment 'the current event ID which is resuming',
    agent_id          bigint unsigned    null comment 'the agent that this execution binds to',
    sync_pattern      tinyint unsigned    null comment 'the sync pattern 1. sync 2. async 3. stream',
    commit_id varchar(255) DEFAULT NULL COMMENT 'draft commit id this execution belongs to',
    KEY `idx_workflow_id_version_mode_created_at` (workflow_id, version, mode, created_at)
);
