# 在mysql服务配置中添加command参数
services:
  mysql:
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    image: mysql:8.0
    container_name: opencoze-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencoze
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./agent/singleagent:/docker-entrypoint-initdb.d
