// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameWorkflowDraft = "workflow_draft"

// WorkflowDraft mapped from table <workflow_draft>
type WorkflowDraft struct {
	ID           int64          `gorm:"column:id;primaryKey;comment:workflow ID" json:"id"`           // workflow ID
	Canvas       string         `gorm:"column:canvas;not null;comment:前端 schema" json:"canvas"`       // 前端 schema
	InputParams  string         `gorm:"column:input_params;comment: 入参 schema" json:"input_params"`   //  入参 schema
	OutputParams string         `gorm:"column:output_params;comment: 出参 schema" json:"output_params"` //  出参 schema
	CreatedAt    int64          `gorm:"column:created_at;not null;autoUpdateTime:milli" json:"created_at"`
	UpdatedAt    int64          `gorm:"column:updated_at;autoUpdateTime:milli" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;autoUpdateTime:milli" json:"deleted_at"`
}

// TableName WorkflowDraft's table name
func (*WorkflowDraft) TableName() string {
	return TableNameWorkflowDraft
}
