/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package workflow

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflow_apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getapidetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchdeleteworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcanvasinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _copyworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _copywktemplateapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdeletestrategyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexampleworkflowlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnodeexecutehistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowprocessMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettracesdkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethistoryschemaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpublishworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listrootspansMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getllmnodefcsettingdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getllmnodefcsettingsmergedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflownodedebugv2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodepanelsearchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodetemplatelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryworkflownodetypesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreleasedworkflowsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _saveworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signimageurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowtestresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowtestrunMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateworkflowmetaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatetreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowdetailinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowreferencesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcardlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chat_flow_roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createchatflowroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletechatflowroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getchatflowroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _project_conversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprojectconversationdefMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowuploadauthtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapigetworkflowrunhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapirunflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapistreamresumeflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapistreamrunflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapichatflowrunMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapigetworkflowinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
