// Code generated by hertz generator.

package developer_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _botMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettypelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _developerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geticonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkdraftbotcommitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _draftbotcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedraftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _duplicatedraftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraftbotdisplayinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdraftbothistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishdraftbotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedraftbotdisplayinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _connectorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishconnectorlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _playgroundMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getonboardingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuploadauthtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserprofilecheckMw() []app.HandlerFunc {
	// your code...
	return nil
}
