// Code generated by hertz generator.

package memory_config

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _memory_configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setmemoryconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmemoryconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}
