// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameKnowledgeDocumentUpdateConfig = "knowledge_document_update_config"

// KnowledgeDocumentUpdateConfig 文档更新配置
type KnowledgeDocumentUpdateConfig struct {
	DocumentID     int64          `gorm:"column:document_id;primaryKey;comment:文档id" json:"document_id"`                // 文档id
	UpdateInterval int32          `gorm:"column:update_interval;not null;comment:更新间隔-小时" json:"update_interval"`       // 更新间隔-小时
	LastUpdateTime int64          `gorm:"column:last_update_time;not null;comment:上次更新时间，单位ms" json:"last_update_time"` // 上次更新时间，单位ms
	NextUpdateTime int64          `gorm:"column:next_update_time;not null;comment:下次更新时间，单位ms" json:"next_update_time"` // 下次更新时间，单位ms
	CreateAt       int64          `gorm:"column:create_at;not null;comment:创建时间，单位ms" json:"create_at"`                 // 创建时间，单位ms
	UpdateAt       int64          `gorm:"column:update_at;not null;comment:更新时间，单位ms" json:"update_at"`                 // 更新时间，单位ms
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment: 删除时间，单位 ms" json:"deleted_at"`                      //  删除时间，单位 ms
	FailReason     string         `gorm:"column:fail_reason;comment:失败原因" json:"fail_reason"`                           // 失败原因
}

// TableName KnowledgeDocumentUpdateConfig's table name
func (*KnowledgeDocumentUpdateConfig) TableName() string {
	return TableNameKnowledgeDocumentUpdateConfig
}
