// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAppVersion = "app_version"

// AppVersion Application Version
type AppVersion struct {
	ID        int64  `gorm:"column:id;primaryKey;comment:APP ID" json:"id"`                                                         // APP ID
	AppID     int64  `gorm:"column:app_id;not null;comment:Application ID" json:"app_id"`                                           // Application ID
	SpaceID   int64  `gorm:"column:space_id;not null;comment:Space ID" json:"space_id"`                                             // Space ID
	OwnerID   int64  `gorm:"column:owner_id;not null;comment:Owner ID" json:"owner_id"`                                             // Owner ID
	IconURI   string `gorm:"column:icon_uri;not null;comment:Icon URI" json:"icon_uri"`                                             // Icon URI
	Name      string `gorm:"column:Name;not null;comment:Application Name" json:"Name"`                                             // Application Name
	Desc      string `gorm:"column:desc;comment:Application Description" json:"desc"`                                               // Application Description
	Version   string `gorm:"column:version;not null;comment:Release Version" json:"version"`                                        // Release Version
	CreatedAt int64  `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
}

// TableName AppVersion's table name
func (*AppVersion) TableName() string {
	return TableNameAppVersion
}
