// Code generated by hertz generator.

package coze

import (
	"context"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"

	"code.byted.org/flow/opencoze/backend/api/model/prompt"
	"code.byted.org/flow/opencoze/backend/application"
)

// UpsertPromptResource .
// @router /api/playground_api/upsert_prompt_resource [POST]
func UpsertPromptResource(ctx context.Context, c *app.RequestContext) {
	var err error
	var req prompt.UpsertPromptResourceRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	if req.Prompt == nil {
		invalidParamRequestResponse(c, "prompt is nil")
		return
	}

	if req.Prompt.GetSpaceID() <= 0 {
		invalidParamRequestResponse(c, "space id is invalid")
		return
	}

	if len(req.Prompt.GetName()) <= 0 {
		invalidParamRequestResponse(c, "name is empty")
		return
	}

	resp, err := application.PromptSVC.UpsertPromptResource(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}

	c.JSON(http.StatusOK, resp)
}
