// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "code.byted.org/flow/opencoze/backend/api/model/plugin/plugin_common"

const TableNameToolVersion = "tool_version"

// ToolVersion Tool Version
type ToolVersion struct {
	ID             int64                         `gorm:"column:id;primaryKey;comment:Primary Key ID" json:"id"`                                                    // Primary Key ID
	ToolID         int64                         `gorm:"column:tool_id;not null;comment:Tool ID" json:"tool_id"`                                                   // Tool ID
	PluginID       int64                         `gorm:"column:plugin_id;not null;comment:Plugin ID" json:"plugin_id"`                                             // Plugin ID
	Name           string                        `gorm:"column:name;not null;comment:Tool Name" json:"name"`                                                       // Tool Name
	Desc           string                        `gorm:"column:desc;comment:Tool Description" json:"desc"`                                                         // Tool Description
	IconURI        string                        `gorm:"column:icon_uri;not null;comment:Icon URI" json:"icon_uri"`                                                // Icon URI
	Version        string                        `gorm:"column:version;not null;comment:Tool Version, e.g. v1.0.0" json:"version"`                                 // Tool Version, e.g. v1.0.0
	SubURLPath     string                        `gorm:"column:sub_url_path;not null;comment:Sub URL Path" json:"sub_url_path"`                                    // Sub URL Path
	RequestMethod  int32                         `gorm:"column:request_method;not null;comment:HTTP Request Method 1get 2post 3put 4delete" json:"request_method"` // HTTP Request Method 1get 2post 3put 4delete
	RequestParams  []*plugin_common.APIParameter `gorm:"column:request_params;comment:Tool Request Parameters;serializer:json" json:"request_params"`              // Tool Request Parameters
	ResponseParams []*plugin_common.APIParameter `gorm:"column:response_params;comment:Tool Response Parameters;serializer:json" json:"response_params"`           // Tool Response Parameters
}

// TableName ToolVersion's table name
func (*ToolVersion) TableName() string {
	return TableNameToolVersion
}
