// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/getkin/kin-openapi/openapi3"
	"gorm.io/gorm"
)

const TableNameToolDraft = "tool_draft"

// ToolDraft Draft Tool
type ToolDraft struct {
	ID              int64               `gorm:"column:id;primaryKey;comment:Tool ID" json:"id"`                                                        // Tool ID
	PluginID        int64               `gorm:"column:plugin_id;not null;comment:Plugin ID" json:"plugin_id"`                                          // Plugin ID
	Name            string              `gorm:"column:name;not null;comment:Tool Name" json:"name"`                                                    // Tool Name
	Desc            string              `gorm:"column:desc;comment:Tool Description" json:"desc"`                                                      // Tool Description
	CreatedAt       int64               `gorm:"column:created_at;not null;autoUpdateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt       int64               `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt       gorm.DeletedAt      `gorm:"column:deleted_at;comment:Delete Time in Milliseconds" json:"deleted_at"`                               // Delete Time in Milliseconds
	SubURL          string              `gorm:"column:sub_url;not null;comment:Sub URL Path" json:"sub_url"`                                           // Sub URL Path
	Method          string              `gorm:"column:method;not null;comment:HTTP Request Method" json:"method"`                                      // HTTP Request Method
	Operation       *openapi3.Operation `gorm:"column:operation;comment:Tool Openapi Operation Schema;serializer:json" json:"operation"`               // Tool Openapi Operation Schema
	DebugStatus     int32               `gorm:"column:debug_status;not null;comment:0:not pass; 1:pass" json:"debug_status"`                           // 0:not pass; 1:pass
	ActivatedStatus int32               `gorm:"column:activated_status;not null;comment:0:activated; 1:deactivated" json:"activated_status"`           // 0:activated; 1:deactivated
}

// TableName ToolDraft's table name
func (*ToolDraft) TableName() string {
	return TableNameToolDraft
}
