/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package space

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	space "github.com/coze-dev/coze-studio/backend/api/model/space"
	"github.com/coze-dev/coze-studio/backend/application/user"
)

// CreateSpace .
// @router /api/space/create [POST]
func CreateSpace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.CreateSpaceRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.CreateSpace(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetSpaceList .
// @router /api/space/list [GET]
func GetSpaceList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.GetSpaceListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(space.GetSpaceListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSpaceDetail .
// @router /api/space/{space_id} [GET]
func GetSpaceDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.GetSpaceDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(space.GetSpaceDetailResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateSpace .
// @router /api/space/{space_id} [PUT]
func UpdateSpace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.UpdateSpaceRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(space.UpdateSpaceResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteSpace .
// @router /api/space/{space_id} [DELETE]
func DeleteSpace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.DeleteSpaceRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(space.DeleteSpaceResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSpaceMembers .
// @router /api/space/{space_id}/members [GET]
func GetSpaceMembers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.GetSpaceMembersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.GetSpaceMembersForSpace(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// InviteMember .
// @router /api/space/{space_id}/members [POST]
func InviteMember(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.InviteMemberRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.InviteMemberForSpace(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdateMemberRole .
// @router /api/space/{space_id}/members/{user_id} [PUT]
func UpdateMemberRole(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.UpdateMemberRoleRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.UpdateMemberRoleForSpace(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// RemoveMember .
// @router /api/space/{space_id}/members/{user_id} [DELETE]
func RemoveMember(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.RemoveMemberRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.RemoveMemberForSpace(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// SearchUsers .
// @router /api/space/search-users [GET]
func SearchUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req space.SearchUsersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := user.UserApplicationSVC.SearchUsersForSpace(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// CheckMemberPermission .
// @router /api/space/{space_id}/permission [GET]
func CheckMemberPermission(ctx context.Context, c *app.RequestContext) {
	// Add debug logs
	println("CheckMemberPermission called!")

	var err error
	var req space.CheckMemberPermissionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		println("BindAndValidate error:", err.Error())
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	println("Request:", req.SpaceID)

	resp, err := user.UserApplicationSVC.CheckMemberPermissionForSpace(ctx, &req)
	if err != nil {
		println("Application error:", err.Error())
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
