// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/coze-dev/coze-studio/backend/infra/contract/document/dataconnector"
	"gorm.io/gorm"
)

const TableNameAuth = "auth"

// Auth auth信息表
type Auth struct {
	ID          int64                        `gorm:"column:id;primaryKey;comment:主键id" json:"id"`                                      // 主键id
	CreatorID   int64                        `gorm:"column:creator_id;not null;comment:用户id" json:"creator_id"`                        // 用户id
	ConnectorID int64                        `gorm:"column:connector_id;not null;comment:数据来源ID" json:"connector_id"`                  // 数据来源ID
	AuthUniqID  string                       `gorm:"column:auth_uniq_id;not null;comment:令牌的uuid" json:"auth_uniq_id"`                 // 令牌的uuid
	Name        string                       `gorm:"column:name;not null;comment:名称" json:"name"`                                      // 名称
	Icon        string                       `gorm:"column:icon;not null;comment:icon" json:"icon"`                                    // icon
	AuthType    string                       `gorm:"column:auth_type;not null;comment:鉴权类型["none"、"oauth"...]" json:"auth_type"`       // 鉴权类型["none"、"oauth"...]
	AuthInfo    *dataconnector.AuthTokenInfo `gorm:"column:auth_info;comment:json 存储鉴权详细配置;serializer:json" json:"auth_info"`          // json 存储鉴权详细配置
	CreatedAt   int64                        `gorm:"column:created_at;not null;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt   int64                        `gorm:"column:updated_at;not null;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt   gorm.DeletedAt               `gorm:"column:deleted_at;not null;comment:Delete Time in Milliseconds" json:"deleted_at"` // Delete Time in Milliseconds
}

// TableName Auth's table name
func (*Auth) TableName() string {
	return TableNameAuth
}
