// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameAppConversionTemplateDraft = "app_conversion_template_draft"

// AppConversionTemplateDraft mapped from table <app_conversion_template_draft>
type AppConversionTemplateDraft struct {
	ID        int64          `gorm:"column:id;primaryKey;comment:id" json:"id"`                                                            // id
	AppID     int64          `gorm:"column:app_id;not null;comment:app id" json:"app_id"`                                                  // app id
	Name      string         `gorm:"column:name;not null;comment:conversion name" json:"name"`                                             // conversion name
	CreatorID int64          `gorm:"column:creator_id;not null;comment:creator id" json:"creator_id"`                                      // creator id
	CreatedAt int64          `gorm:"column:created_at;not null;autoCreateTime:milli;comment:create time in millisecond" json:"created_at"` // create time in millisecond
	UpdatedAt int64          `gorm:"column:updated_at;autoUpdateTime:milli;comment:update time in millisecond" json:"updated_at"`          // update time in millisecond
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:delete time in millisecond" json:"deleted_at"`                               // delete time in millisecond
}

// TableName AppConversionTemplateDraft's table name
func (*AppConversionTemplateDraft) TableName() string {
	return TableNameAppConversionTemplateDraft
}
