// Code generated by hertz generator.

package memory_config

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	memory_config "github.com/coze-dev/coze-studio/backend/api/model/memory_config"
)

// GetMemoryConfig .
// @router /api/memory-config/{user_id} [GET]
func GetMemoryConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req memory_config.GetMemoryConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(memory_config.GetMemoryConfigResponse)

	c.JSON(consts.StatusOK, resp)
}

// SetMemoryConfig .
// @router /api/memory-config/set [POST]
func SetMemoryConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req memory_config.SetMemoryConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(memory_config.SetMemoryConfigResponse)

	c.JSON(consts.StatusOK, resp)
}
