/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package template_publish

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _templateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmytemplatelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishastemplateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetemplateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkpublishstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unpublishtemplateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadtemplateiconMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _storeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkstorepublishstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstoretemplatelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishtostoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unpublishfromstoreMw() []app.HandlerFunc {
	// your code...
	return nil
}
