// code generated by go run gen.go; DO NOT EDIT.

package stream

import (
	"context"

	"code.byted.org/flow/opencoze/backend/pkg/lang/gg/internal/constraints"
	"code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter"
)

// Orderable is a constraints.Ordered variant of Comparable.
type Orderable[T constraints.Ordered] struct {
	Comparable[T]
}

// FromIter wraps an [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Iter] to [Stream].
func FromOrderableIter[T constraints.Ordered](i iter.Iter[T]) Orderable[T] {
	return Orderable[T]{FromComparableIter(i)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.FromSlice].
func FromOrderableSlice[T constraints.Ordered](s []T) Orderable[T] {
	return Orderable[T]{FromComparableSlice(s)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.StealSlice].
func StealOrderableSlice[T constraints.Ordered](s []T) Orderable[T] {
	return Orderable[T]{StealComparableSlice(s)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.FromMapValues].
func FromOrderableMapValues[I comparable, T constraints.Ordered](m map[I]T) Orderable[T] {
	return Orderable[T]{FromComparableMapValues(m)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.FromChan].
func FromOrderableChan[T constraints.Ordered](ctx context.Context, ch <-chan T) Orderable[T] {
	return Orderable[T]{FromComparableChan(ctx, ch)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Repeat].
func RepeatOrderable[T constraints.Ordered](v T) Orderable[T] {
	return Orderable[T]{RepeatComparable(v)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.MapInplace].
func (s Orderable[T]) Map(f func(T) T) Orderable[T] {
	return Orderable[T]{s.Comparable.Map(f)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.FlatMap].
func (s Orderable[T]) FlatMap(f func(T) []T) Orderable[T] {
	return Orderable[T]{s.Comparable.FlatMap(f)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Filter].
func (s Orderable[T]) Filter(f func(T) bool) Orderable[T] {
	return Orderable[T]{s.Comparable.Filter(f)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Reverse].
func (s Orderable[T]) Reverse() Orderable[T] {
	return Orderable[T]{s.Comparable.Reverse()}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Take].
func (s Orderable[T]) Take(n int) Orderable[T] {
	return Orderable[T]{s.Comparable.Take(n)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Drop].
func (s Orderable[T]) Drop(n int) Orderable[T] {
	return Orderable[T]{s.Comparable.Drop(n)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Concat].
//
// BUG: This function is marked as "//go:noinline" bacause a community bug is
// triggered in [Tango Beast Mode], see https://code.byted.org/lang/go/issues/255
//
// [Tango Beast Mode]: https://bytedance.feishu.cn/wiki/wikcnoMjJbw3D9bV8aU8sDsJBNc
//
//go:noinline
func (s Orderable[T]) Concat(ss ...Orderable[T]) Orderable[T] {
	conv := func(c Orderable[T]) Comparable[T] {
		return c.Comparable
	}
	tmp := iter.ToSlice(iter.Map(conv, iter.FromSlice(ss)))
	return Orderable[T]{s.Comparable.Concat(tmp...)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Zip].
func (s Orderable[T]) Zip(f func(T, T) T, another Orderable[T]) Orderable[T] {
	return Orderable[T]{s.Comparable.Zip(f, another.Comparable)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Intersperse].
func (s Orderable[T]) Intersperse(sep T) Orderable[T] {
	return Orderable[T]{s.Comparable.Intersperse(sep)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Append].
func (s Orderable[T]) Append(tail T) Orderable[T] {
	return Orderable[T]{s.Comparable.Append(tail)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Prepend].
func (s Orderable[T]) Prepend(head T) Orderable[T] {
	return Orderable[T]{s.Comparable.Prepend(head)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.TakeWhile].
func (s Orderable[T]) TakeWhile(f func(T) bool) Orderable[T] {
	return Orderable[T]{s.Comparable.TakeWhile(f)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.DropWhile].
func (s Orderable[T]) DropWhile(f func(T) bool) Orderable[T] {
	return Orderable[T]{s.Comparable.DropWhile(f)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.SortBy].
func (s Orderable[T]) SortBy(less func(T, T) bool) Orderable[T] {
	return Orderable[T]{s.Comparable.SortBy(less)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.UniqBy].
func (s Orderable[T]) UniqBy(f func(T) any) Orderable[T] {
	return Orderable[T]{s.Comparable.UniqBy(f)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Shuffle].
func (s Orderable[T]) Shuffle() Orderable[T] {
	return Orderable[T]{s.Comparable.Shuffle()}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.FromMapKeys].
func FromOrderableMapKeys[T constraints.Ordered, I any](m map[T]I) Orderable[T] {
	return Orderable[T]{FromMapKeys(m)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Uniq].
func (s Orderable[T]) Uniq() Orderable[T] {
	return Orderable[T]{s.Comparable.Uniq()}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.Remove].
func (s Orderable[T]) Remove(v T) Orderable[T] {
	return Orderable[T]{s.Comparable.Remove(v)}
}

// See function [pkg/code.byted.org/flow/opencoze/backend/pkg/lang/gg/iter.RemoveN].
func (s Orderable[T]) RemoveN(v T, n int) Orderable[T] {
	return Orderable[T]{s.Comparable.RemoveN(v, n)}
}
